variable "env" {}
variable "instance_type" {}
variable "name" {}
variable "zone_id" {}
variable "port_no" {}
variable "port_no_of_ssh" {}
variable "port_no_of_node_exporter" {}
variable "token" {}
variable "prometheus_server" {}